### ISSUE TITLE
Crashes for users with more than 1 DVR

### ISSUE THREAD

**Issue by timlarson345** [codethug/SimpleTv#19]
Tried in on my system which has two SimpleTV v1 devices.  Here's what I get

```
C:\>SimpleTv.Downloader.0.2.1.exe -u #####@#### -
p "########" -d c:\temp -s "Unfor*"
Logging In
Loading Media Servers
Locating Media Server SimpleTV One
Testing Media Server Locations for SimpleTV One
Locating Media Server Simple.TV Two
Testing Media Server Locations for Simple.TV Two
Downloading Unforgivable Blackness: The Rise and Fall of Jack Johnson
=======================================================
Unhandled Exception: System.InvalidOperationException: Sequence contains no elem
ents
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at SimpleTv.Sdk.Http.SimpleTvHttpClient.<>c__DisplayClass16_0.<GetEpisodes>b_
_0(HtmlNode article) in C:\Users\tim.larson\Documents\GitHub\SimpleTv\SimpleTv.S
dk\Http\SimpleTvHttpClient.cs:line 283
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SimpleTv.Sdk.Http.SimpleTvHttpClient.GetEpisodes(Show show) in C:\Users\ti
m.larson\Documents\GitHub\SimpleTv\SimpleTv.Sdk\Http\SimpleTvHttpClient.cs:line
281
   at SimpleTv.Downloader.Program.Main(String[] args)
```

**Comment by dgreenb** [comment]
I only have 1 DVR, but you said on the forum to attach my output to this bug.  Also, I had to change the extension to get it to upload.

Hope this helps!

[SimpleTv.DownloadLog.2016-03-19_22-29-59.json.txt](https://github.com/codethug/SimpleTv/files/181080/SimpleTv.DownloadLog.2016-03-19_22-29-59.json.txt)

**Comment by timlarson345** [comment]
@dgreenb , version 0.2.4 should fix the exception you found related to parsing the Current Software Version.  Thanks for the log file - it was very helpful.  [Download the latest version](https://github.com/codethug/SimpleTv/releases) to see if your issue is resolved.
